services:
  mysql:
    image: mysql:5.7
    container_name: hive-metastore-mysql
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: metastore_db
      MYSQL_USER: hive
      MYSQL_PASSWORD: hive
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    networks:
      - hive-network
  minio:
    container_name: trino-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ./volumes/minio:/minio_data
    command: minio server --console-address ":9001" --address ":9000" /minio_data
    ports:
      - 19090:9000
      - 19001:9001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - hive-network
  hive-metastore:
    image: hive-metastore:3.1.3
    container_name: hive-metastore
    depends_on:
      - mysql
      - minio
    links:
      - minio
    ports:
      - "9083:9083"
    environment:
      DB_DRIVER: mysql
      DB_CONNECTION_URL: jdbc:mysql://mysql:3306/metastore_db
      DB_USER: hive
      DB_PASS: hive
      METASTORE_DB_TYPE: mysql
      SERVICE_NAME: metastore
    volumes:
      - ./metastore/mysql-connector-java-5.1.49.jar:/opt/mysql-connector-java-5.1.49.jar
      - ./metastore/metastore-site.xml:/opt/hive-metastore/conf/metastore-site.xml
      - ./metastore/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./metastore/init-schema.sh:/opt/hive-metastore/init-schema.sh
    entrypoint: 
      - "/bin/bash"
      - "-c"
      - "/opt/hive-metastore/init-schema.sh && /opt/hive-metastore/bin/start-metastore"
    networks:
      - hive-network
      
  coordinator:
    image: trinodb/trino:470
    container_name: coordinator
    depends_on:
      - hive-metastore
    links:
      - "hive-metastore"
    ports:
      - "18080:8080"
    volumes:
      - ./trino-conf/catalog:/etc/trino/catalog
      - ./trino-conf/coordinator/config.properties:/etc/trino/config.properties
      - ./trino-conf/coordinator/jvm.config:/etc/trino/jvm.config
      - ./trino-conf/coordinator/log.properties:/etc/trino/log.properties
      - ./trino-conf/coordinator/node.properties:/etc/trino/node.properties
      - ./volumes/trino/coordinator:/etc/trino
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 16G
        reservations:
          cpus: '2.0'
          memory: 12G
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - hive-network
  
  worker1:
    image: trinodb/trino:470
    container_name: worker1
    depends_on:
      coordinator:
        condition: service_healthy
    links:
      - "hive-metastore"
      - coordinator
    volumes:
      - ./trino-conf/catalog:/etc/trino/catalog
      - ./trino-conf/worker/config.properties:/etc/trino/config.properties
      - ./trino-conf/worker/jvm.config:/etc/trino/jvm.config
      - ./trino-conf/worker/log.properties:/etc/trino/log.properties
      - ./trino-conf/worker/node1.properties:/etc/trino/node.properties
      - ./volumes/trino/worker1:/etc/trino
    deploy:
      resources:
        limits:
          cpus: '8.0'
          memory: 22G
        reservations:
          cpus: '4.0'
          memory: 20G
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - hive-network

  worker2:
    image: trinodb/trino:470
    container_name: worker2
    depends_on:
      coordinator:
        condition: service_healthy
      worker1:
        condition: service_started
    links:
      - "hive-metastore"
      - coordinator
    volumes:
      - ./trino-conf/catalog:/etc/trino/catalog
      - ./trino-conf/worker/config.properties:/etc/trino/config.properties
      - ./trino-conf/worker/jvm.config:/etc/trino/jvm.config
      - ./trino-conf/worker/log.properties:/etc/trino/log.properties
      - ./trino-conf/worker/node2.properties:/etc/trino/node.properties
      - ./volumes/trino/worker2:/etc/trino
    deploy:
      resources:
        limits:
          cpus: '8.0'
          memory: 22G
        reservations:
          cpus: '4.0'
          memory: 20G
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - hive-network

networks:
  hive-network:
    driver: bridge
