FROM openjdk:11-slim

RUN apt-get update -y && apt-get install -y curl --no-install-recommends && rm -rf /var/lib/apt/lists/*

COPY hadoop-3.2.4.tar.gz hive-standalone-metastore-3.1.3-bin.tar.gz mysql-connector-java-8.0.27.jar /opt

WORKDIR /opt

RUN tar xzf hadoop-3.2.4.tar.gz && ln -s /opt/hadoop-3.2.4 /opt/hadoop && tar xzf hive-standalone-metastore-3.1.3-bin.tar.gz && ln -s /opt/apache-hive-metastore-3.1.3-bin /opt/hive-metastore && rm /opt/hadoop-3.2.4.tar.gz /opt/hive-standalone-metastore-3.1.3-bin.tar.gz

RUN rm -r /opt/hadoop/share/doc && ln -s /opt/hadoop/share/hadoop/tools/lib/aws-java-sdk-bundle-1.11.901.jar /opt/hadoop/share/hadoop/common/lib/ && ln -s /opt/hadoop/share/hadoop/tools/lib/hadoop-aws-3.2.4.jar /opt/hadoop/share/hadoop/common/lib/

RUN rm /opt/hive-metastore/lib/guava-19.0.jar && cp /opt/hadoop/share/hadoop/common/lib/guava-27.0-jre.jar /opt/hive-metastore/lib

RUN ln -s /opt/mysql-connector-java-8.0.27.jar /opt/hadoop/share/hadoop/common/lib/ && ln -s /opt/mysql-connector-java-8.0.27.jar /opt/hive-metastore/lib/

ENV HADOOP_VERSION=3.2.4 \
	HIVE_METASTORE_VERSION=3.1.3 \
	HADOOP_HOME="/opt/hadoop" \
	PATH="/opt/hadoop/bin:${PATH}"
